[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.1",
    "django-debug-toolbar>=7.1.1",
    "django-environ>=0.14.0",
    "djangorestframework>=3.18.0",
    "faker>=40.38.0",
    "gunicorn>=26.1.0",
    "locust>=2.46.5",
    "psycopg[binary]>=3.3.4",
]
