name: Build React App

# Applies to all jobs and run steps in this file
defaults:
  run:
    working-directory: ./frontend

# 1. Trigger the workflows on pushes or PRs to the main branch
on:
  push:
    branches: ["main"]
  # pull_request:
  #   branches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # step1: Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # step2: Setup node.js environment
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm' # speeds up builds by caching node_modules
          cache-dependency-path: frontend/package-lock.json
      
      # Step3: Show current directory
      - name: Show current directory
        run: |
          pwd
          ls -la
      # step#: install dependencies
      - name: Install dependencies
        run: npm ci

      # Step4: Run the build script
      - name: Build project
        run: npm run build

      # Step5: Upload artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-dist
          path: /home/runner/work/pulumi-crator/pulumi-crator/frontend/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # step1: Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # step2: Download the build artifacts
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: react-dist
          path: dist

  
