name: Build & Deploy React App

# Applies to all jobs and run steps in this file
defaults:
  run:
    working-directory: ./frontend

# 1. Trigger the workflows on pushes or PRs to the main branch
on:
  push:
    branches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # step1: Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # step2: Setup node.js environment
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm' # speeds up builds by caching node_modules
          cache-dependency-path: frontend/package-lock.json
      
      # Step3: Show current directory
      - name: Show current directory
        run: |
          pwd
          ls -la
      # step#: install dependencies
      - name: Install dependencies
        run: npm ci

      # Step4: Run the build script
      - name: Build project
        run: npm run build

      # Step5: Upload artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-dist
          path: frontend/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # step1: Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # step2: Download the build artifacts
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: react-dist
          path: frontend/dist

      # Step3: To verify the downloaded files from artifact
      - name: Verify downloaded artifact
        run: |
          pwd
          ls -R dist
  
      #Step4: Pulumi Setup
      - name: Pulumi Setup download python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install UV
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: AWS Authenticate
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          custom-tags: '{"Environment": "Dev", "Team": "Pulumi"}'

      - name: Debug Pulumi
        working-directory: ${{ github.workspace }}/infra
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        run: |
          pulumi login s3://pulumi-bootstrap-state-mainter

          echo "Current backend:"
          pulumi whoami

          echo "Stacks:"
          uv run pulumi stack ls

          echo "Current stack:"
          uv run pulumi stack select dev

          echo "Outputs:"
          uv run pulumi stack output

      - name: Pulumi Save track file
        run: |
            pulumi login s3://pulumi-bootstrap-state-mainter

      - name: Get Bucket name
        id: bucket_name
        run: |
            # Fetch specific bucket_name value
            uv run pulumi stack select dev
            bucket_name=$(uv run pulumi stack output bucket_name --json)

            echo "bucket name=$bucket_name" >> $GITHUB_OUTPUT
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{secrets.PULUMI_CONFIG_PASSPHRASE}}
        working-directory: ${{github.workspace }}/infra