# name: Deploy react app

# jobs:
#   deploy:
#     needs:  build
#     runs-on: ubuntu@latest
#     steps:
#       # step1: Check out your repository code
#       - name: Download from artifact
#         uses: actions/download-artifact@v4
#         with:
#             name: react-dist
#             path: dist/
